
all: nurses ex1 ex2

nurses: nurses.pl
	swipl -quiet -O -g main --stand_alone=true -o nurses -c nurses.pl
	
ex1: ex1.pl
	swipl -quiet -O -g main --stand_alone=true -o ex1 -c ex1.pl
	
ex2: ex2.pl
	swipl -quiet -O -g main --stand_alone=true -o ex2 -c ex2.pl
