
all: banner gangsters banner_v1

gangsters: gangsters.pl
	swipl -quiet -O -g main --stand_alone=true -o gangsters  -c gangsters.pl

banner: banner.pl
	swipl -quiet -O -g main --stand_alone=true -o banner  -c banner.pl

banner_v1: banner_v1.pl
	swipl -quiet -O -g main --stand_alone=true -o banner_v1  -c banner_v1.pl
