
all: banner gangsters

gangsters: gangsters.pl
	swipl -quiet -O -g main --stand_alone=true -o gangsters  -c gangsters.pl

banner: banner.pl
	swipl -quiet -O -g main --stand_alone=true -o banner  -c banner.pl
